//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sql_Dependency_Entity_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpChangesTime
    {
        public int Id { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public string ActionName { get; set; }
    }
}
